
import "./globals.css";
import { Inter } from "next/font/google";
import { InternetIdentityProvider } from "ic-use-internet-identity";
import { Toaster } from "react-hot-toast";
import Actors from "./ic/Actors";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        {/* <InternetIdentityProvider>
         <Actors> */}
          {children}
         {/* </Actors>
        </InternetIdentityProvider> */}
        
      </body>
    </html>
  );
}
